[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/tv/:canal.m3u8"
  to = "/.netlify/functions/generate_m3u8?canal=:canal"
  status = 200
  query = { canal = ":canal" }
  force = true

