[[headers]]
  for = "/tv/*.m3u8"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/x-mpegURL"
    Cache-Control = "max-age=86400"

[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/tv/telefuturo.m3u8"
  to = "https://panel-inv.netlify.app/.netlify/functions/generate_m3u8?canal=telefuturo"
  status = 200
  force = true

[[redirects]]
  from = "/tv/genpy.m3u8"
  to = "https://panel-inv.netlify.app/.netlify/functions/generate_m3u8?canal=genpy"
  status = 200
  force = true

[[redirects]]
  from = "/tv/poputv.m3u8"
  to = "https://panel-inv.netlify.app/.netlify/functions/generate_m3u8?canal=poputv"
  status = 200
  force = true

[[redirects]]
  from = "/tv/latele.m3u8"
  to = "https://panel-inv.netlify.app/.netlify/functions/generate_m3u8?canal=latele"
  status = 200
  force = true
